//! Grimoire files: reproducible SPQL recipes.
//!
//! A grimoire is a plain-text SPQL script (`~/.vitriol/grimoires/<name>.grimoire`)
//! capturing the exact committed transformations needed to reproduce a sculpted
//! model. `RECORD > name` starts capturing committed ops; `STOP` writes the
//! file; `PLAY > file` parses and runs it (probe by default, `COMMIT > PLAY`
//! applies). Files are git-trackable and tiny (recipe, not weights).

use std::fs;
use std::path::{Path, PathBuf};

/// Directory of grimoires under a home dir.
pub fn grimoires_dir(home: &Path) -> PathBuf {
    home.join(".vitriol/grimoires")
}

/// A valid grimoire file name (alnum, hyphen, underscore, dots allowed).
fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.')
}

/// Write a grimoire file; returns the absolute path written.
pub fn write(home: &Path, name: &str, lines: &[String]) -> Result<PathBuf, String> {
    if !valid_name(name) {
        return Err(format!("invalid grimoire name '{name}'"));
    }
    let dir = grimoires_dir(home);
    fs::create_dir_all(&dir).map_err(|e| format!("mkdir {}: {e}", dir.display()))?;
    let path = dir.join(format!("{name}.grimoire"));
    let mut text = format!("// {name}.grimoire\n// generated by Officina {}\n", stamp());
    for l in lines {
        text.push_str(l);
        text.push('\n');
    }
    fs::write(&path, text).map_err(|e| format!("write {}: {e}", path.display()))?;
    Ok(path)
}

/// Read a grimoire file's command lines (skipping comments/blanks).
pub fn read(path: &Path) -> Result<Vec<String>, String> {
    let text = fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    Ok(text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with("//"))
        .map(str::to_string)
        .collect())
}

/// List grimoire files (stem names) in the dir; missing dir -> empty.
pub fn list(home: &Path) -> Vec<String> {
    let Ok(entries) = fs::read_dir(grimoires_dir(home)) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .flatten()
        .filter(|e| e.path().extension().and_then(|x| x.to_str()) == Some("grimoire"))
        .filter_map(|e| {
            e.path()
                .file_stem()
                .map(|s| s.to_string_lossy().into_owned())
        })
        .collect();
    names.sort();
    names
}

/// UTC timestamp for the file header.
fn stamp() -> String {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs().to_string())
        .unwrap_or_else(|_| "unknown".into())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_home(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!("officina_grimoire_test_{name}"))
    }

    #[test]
    fn write_read_roundtrip() {
        let home = tmp_home("roundtrip");
        let _ = fs::remove_dir_all(&home);
        let path = write(
            &home,
            "systems-opt",
            &["DISSOLVE > layer.12.mlp wanda 0.35".into(), "MAP".into()],
        )
        .unwrap();
        let lines = read(&path).unwrap();
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0], "DISSOLVE > layer.12.mlp wanda 0.35");
        let _ = fs::remove_dir_all(&home);
    }

    #[test]
    fn list_returns_sorted_stems() {
        let home = tmp_home("list");
        let _ = fs::remove_dir_all(&home);
        write(&home, "b-second", &["MAP".into()]).unwrap();
        write(&home, "a-first", &["MAP".into()]).unwrap();
        let names = list(&home);
        assert_eq!(names, vec!["a-first", "b-second"]);
        let _ = fs::remove_dir_all(&home);
    }

    #[test]
    fn invalid_names_rejected() {
        let home = tmp_home("invalid");
        assert!(write(&home, "bad name", &[]).is_err());
        assert!(write(&home, "", &[]).is_err());
        let _ = fs::remove_dir_all(&home);
    }
}
