# Kernel FFI Implementations
[printk]
impl = "brief_printk"

[pci_get_device]
impl = "brief_pci_get_device"

[pci_iomap]
impl = "brief_pci_iomap"

[pci_iounmap]
impl = "brief_pci_iounmap"

[pci_dev_put]
impl = "brief_pci_dev_put"

[read_reg_at]
impl = "brief_read_reg_at"

[mb]
impl = "brief_mb"

[rmb]
impl = "brief_rmb"

[wmb]
impl = "brief_wmb"
