/* C application - generated by Brief */
/* Target: hosted */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

/* FFI Function Declarations */

/* Constant Definitions */
#define GPU_VENDOR 4318
#define GPU_DEVICE 7042
#define BAR_CONTROL_SIZE 16777216
#define BAR_DATA_SIZE 268435456
#define MAX_LAYERS 1000
extern void printk(char * fmt);
extern uint32_t pci_get_device(uint32_t vendor, uint32_t device, uint32_t from);
extern uint32_t pci_iomap(uint32_t dev, uint32_t bar, uint32_t len);
extern bool pci_iounmap(uint32_t dev, uint32_t addr);
extern bool pci_dev_put(uint32_t dev);
extern uint32_t read_reg_at(uint32_t addr);
extern void mb(void);
extern void rmb(void);
extern void wmb(void);

typedef struct {
    uint32_t gpu_dev;
    uint32_t gpu_bar_addr;
    uint32_t gpu_ctrl_addr;
    bool gpu_mapped;
    bool dma_active;
    uint32_t current_layer;
    uint32_t gpu_status;
} State;

static State *state = NULL;

void state_init(void) {
    state->gpu_dev = 0;
    state->gpu_bar_addr = 0;
    state->gpu_ctrl_addr = 0;
    state->gpu_mapped = false;
    state->dma_active = false;
    state->current_layer = 0;
    state->gpu_status = 0;
}

bool init(void) {    /* pre: Eq(Identifier("gpu_mapped"), Bool(false)) */
    printk("VITRIOL: Visita Interiora Terrae...\n");
    printk("VITRIOL: Separating Control Plane (BAR 0) from Data Plane (BAR 1)\n");
    uint32_t result = pci_get_device(4318, 7042, 0);
    if ((result > 0)) {
    state->gpu_dev = result;
    printk("VITRIOL: GPU device found (10de:1b82)\n");
    }
    if ((state->gpu_dev > 0)) {
    uint32_t ctrl_result = pci_iomap(state->gpu_dev, 0, 16777216);
    if ((ctrl_result > 0)) {
    state->gpu_ctrl_addr = ctrl_result;
    printk("VITRIOL: Control Plane (BAR 0) mapped at 16MB - READ ONLY\n");
    }
    }
    if ((state->gpu_dev > 0)) {
    uint32_t data_result = pci_iomap(state->gpu_dev, 1, 268435456);
    if ((data_result > 0)) {
    state->gpu_bar_addr = data_result;
    state->gpu_mapped = true;
    printk("VITRIOL: Data Plane (BAR 1) mapped at 256MB - SAFE for streaming\n");
    printk("VITRIOL: Mercurial Bridge established - Ready to stream weights\n");
    }
    }
    /* transaction complete */
    /* post: Eq(Identifier("gpu_mapped"), Bool(true)) */
    return true;
}

bool monitor_gpu(void) {    /* pre: Gt(Identifier("gpu_ctrl_addr"), Integer(0)) */
    uint32_t result = read_reg_at(state->gpu_ctrl_addr);
    if ((result > 0)) {
    state->gpu_status = result;
    printk("VITRIOL: GPU status register = 0x%x\n", result);
    }
    /* transaction complete */
    /* post: Eq(Identifier("gpu_status"), PriorState("value")) */
    return true;
}

bool stream_layer(void) {    /* pre: And(Not(Identifier("dma_active")), Lt(Identifier("current_layer"), Identifier("MAX_LAYERS"))) */
    state->dma_active = true;
    printk("VITRIOL: Streaming layer %d through Data Plane (BAR 1)\n", state->current_layer);
    /* transaction complete */
    /* post: Eq(Identifier("dma_active"), Bool(true)) */
    return true;
}

bool dma_done(void) {    /* pre: Eq(Identifier("dma_active"), Bool(true)) */
    state->dma_active = false;
    /* transaction complete */
    /* post: Eq(Identifier("dma_active"), Bool(false)) */
    return true;
}

bool cleanup(void) {    /* pre: Eq(Identifier("gpu_mapped"), Bool(true)) */
    if ((state->gpu_bar_addr != 0)) {
    /* FFI call to pci_iounmap with error handling */
    bool _result_pci_iounmap = pci_iounmap(state->gpu_dev, state->gpu_bar_addr);
    if ((_result_pci_iounmap >= -1 && _result_pci_iounmap <= -1)) goto ffi_error_pci_iounmap;
    goto ffi_ok_pci_iounmap;
ffi_error_pci_iounmap:
    /* FFI error occurred for pci_iounmap */
ffi_ok_pci_iounmap:
    }
    if ((state->gpu_ctrl_addr != 0)) {
    /* FFI call to pci_iounmap with error handling */
    bool _result_pci_iounmap = pci_iounmap(state->gpu_dev, state->gpu_ctrl_addr);
    if ((_result_pci_iounmap >= -1 && _result_pci_iounmap <= -1)) goto ffi_error_pci_iounmap;
    goto ffi_ok_pci_iounmap;
ffi_error_pci_iounmap:
    /* FFI error occurred for pci_iounmap */
ffi_ok_pci_iounmap:
    }
    if ((state->gpu_dev != 0)) {
    /* FFI call to pci_dev_put with error handling */
    bool _result_pci_dev_put = pci_dev_put(state->gpu_dev);
    if ((_result_pci_dev_put >= -1 && _result_pci_dev_put <= -1)) goto ffi_error_pci_dev_put;
    goto ffi_ok_pci_dev_put;
ffi_error_pci_dev_put:
    /* FFI error occurred for pci_dev_put */
ffi_ok_pci_dev_put:
    }
    printk("VITRIOL: Houdoe hé.\n");
    state->gpu_mapped = false;
    /* transaction complete */
    /* post: Eq(Identifier("gpu_mapped"), Bool(false)) */
    return true;
}

static void init_wrapper(void) {
    state = (State *)malloc(sizeof(State));
    state_init();
}

int main(void) {
    init_wrapper();
    return 0;
}
