#!/usr/bin/env node
// build-patch.mjs — regenerates runtime/patched/interactive-mode.officina.js
// from the pristine reference + the P1-P3 patch list (layout fork step 2).
//
// Keeping the patch APPLICATION scripted (instead of hand-editing the vendor
// copy) means re-basing on a pi upgrade is: bump the pin, re-run this script,
// fix any anchor that no longer matches. Anchors are asserted — a silent
// partial patch is impossible.
//
// Usage: node ../runtime/build-patch.mjs   (cwd: officina/runtime)

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const refPath = join(here, "upstream", "interactive-mode.reference.js");
const outDir = join(here, "patched");
const outPath = join(outDir, "interactive-mode.officina.js");

let src = readFileSync(refPath, "utf-8");

const header = `// [officina] PATCHED VENDOR COPY - generated by runtime/build-patch.mjs.
// Source: @earendil-works/pi-coding-agent 0.83.0
//         dist/modes/interactive/interactive-mode.js (Apache-2.0)
// Pristine reference: runtime/upstream/interactive-mode.reference.js
// Patches applied below are marked with [officina P1..P3]. Re-base by
// re-running build-patch.mjs after bumping the pin; anchors assert.
`;

function patch(name, anchor, replacement) {
  if (!src.includes(anchor)) {
    throw new Error(`patch ${name}: anchor not found`);
  }
  src = src.replace(anchor, replacement);
}

// ── P1: docked two-column layout ──────────────────────────────────────────
// [officina P1] placeholder wiring: the chat/editor column renders inside a
// Columns split with the docked sidebar column. Full sidebar component
// lands with P3 plumbing; this patch establishes the seam.
patch(
  "P1 seam",
  "this.renderWidgets(); // Initialize with default spacer",
  `this.renderWidgets(); // Initialize with default spacer
       // [officina P1] docked layout seam (see runtime/columns.ts); sidebar
       // component is attached by the session-panel adapter via ui.setSidebar.` +
    "",
);

// ── P2: composer pinned to the viewport floor ────────────────────────────
// [officina P2] reserved for the in-layout pin (the wrapper newline-reserve
// remains the classic-mode fallback until this lands).

// ── P3: ui.setSidebar plumbing ───────────────────────────────────────────
// The docked sidebar is a dedicated Container in the layout, fed by
// ui.setSidebar(lines) from extensions (session-panel). Step 3 mounts it in
// the vertical stack (below the widgets, above the footer); step 4's P1
// re-parents it beside chat+editor when Columns lands.

patch(
  "P3 field",
  `    widgetContainerAbove;
    widgetContainerBelow;`,
  `    widgetContainerAbove;
    widgetContainerBelow;
    // [officina P3] docked sidebar column (fed via ui.setSidebar)
    sidebarContainer;`,
);

patch(
  "P3 container init",
  `        this.widgetContainerAbove = new Container();
        this.widgetContainerBelow = new Container();`,
  `        this.widgetContainerAbove = new Container();
        this.widgetContainerBelow = new Container();
        // [officina P3] docked sidebar column
        this.sidebarContainer = new Container();`,
);

patch(
  "P3 layout mount",
  `        this.ui.addChild(this.widgetContainerBelow);
        this.ui.addChild(this.footer);`,
  `        this.ui.addChild(this.widgetContainerBelow);
        // [officina P3] docked sidebar column (re-parented by [officina P1])
        this.ui.addChild(this.sidebarContainer);
        this.ui.addChild(this.footer);`,
);

patch(
  "P3 setter method",
  `    // Maximum total widget lines to prevent viewport overflow`,
  `    // [officina P3] Docked sidebar content from extensions. lines ===
    // undefined clears it. Truncation matches the widget budget.
    setExtensionSidebar(lines) {
        this.sidebarContainer.clear();
        if (lines && lines.length > 0) {
            for (const line of lines.slice(0, InteractiveMode.MAX_WIDGET_LINES)) {
                this.sidebarContainer.addChild(new Text(line, 1, 0));
            }
            if (lines.length > InteractiveMode.MAX_WIDGET_LINES) {
                this.sidebarContainer.addChild(new Text(theme.fg("muted", "... (sidebar truncated)"), 1, 0));
            }
        }
        this.ui.requestRender();
    }
    // Maximum total widget lines to prevent viewport overflow`,
);

patch(
  "P3 ui surface",
  `            setWidget: (key, content, options) => this.setExtensionWidget(key, content, options),`,
  `            setWidget: (key, content, options) => this.setExtensionWidget(key, content, options),
            setSidebar: (lines) => this.setExtensionSidebar(lines),`,
);

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, header + src);
console.log(`[build-patch] wrote ${outPath} (${src.split("\n").length} lines)`);
