#!/usr/bin/env node
// build-patch.mjs — regenerates runtime/patched/interactive-mode.officina.js
// from the pristine reference + the P1-P3 patch list (layout fork step 2).
//
// Keeping the patch APPLICATION scripted (instead of hand-editing the vendor
// copy) means re-basing on a pi upgrade is: bump the pin, re-run this script,
// fix any anchor that no longer matches. Anchors are asserted — a silent
// partial patch is impossible.
//
// Usage: node ../runtime/build-patch.mjs   (cwd: officina/runtime)

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const refPath = join(here, "upstream", "interactive-mode.reference.js");
const outDir = join(here, "patched");
const outPath = join(outDir, "interactive-mode.officina.js");

let src = readFileSync(refPath, "utf-8");

const header = `// [officina] PATCHED VENDOR COPY - generated by runtime/build-patch.mjs.
// Source: @earendil-works/pi-coding-agent 0.83.0
//         dist/modes/interactive/interactive-mode.js (MIT)
// Pristine reference: runtime/upstream/interactive-mode.reference.js
// Patches applied below are marked with [officina P1..P10]:
//   P1 docked two-column split, P2 composer floor-pin, P3 ui.setSidebar
//   plumbing, P4 sidebar bottom-anchor, P5 tool-execution display names
//   (separate file), P6 sidebar visibility bridge, P7 native ANSI/merge
//   delegation, P8 mouse reporting, P9 dynamic mode tint, P10 scrollback.
// Re-base by re-running build-patch.mjs after bumping the pin; anchors assert.
`;

function patch(name, anchor, replacement) {
  if (!src.includes(anchor)) {
    throw new Error(`patch ${name}: anchor not found`);
  }
  src = src.replace(anchor, replacement);
}

// ── P1: docked two-column layout ──────────────────────────────────────────
// The chat/pending/status/widgets/editor containers are re-parented into an
// OfficinaSplit (bottom of file) which renders main column + docked sidebar
// side-by-side (JS port of runtime/columns.ts, extended for OSC/APC
// zero-width sequences). The header, loaded-resources, and footer stay full
// width. Auto-hides the sidebar below 100 columns.

// ── P2: composer pinned to the viewport floor ────────────────────────────
// The TUI viewport is bottom-anchored, so the composer pins naturally once
// total content fills the screen; OfficinaSplit inserts blank filler rows
// above the editor block to guarantee that on a fresh session (replaces the
// launcher's newline-reserve, which stays as the classic-mode fallback).

// Zero-width-safe width helpers + the split component. Injected at the top
// of the module so the InteractiveMode constructor can reference them.
const officinaSplitJs = String.raw`
// [officina P1] OfficinaSplit — docked two-column layout. JS port of
// runtime/columns.ts (this repo, original work) with OSC/APC-aware widths:
// pi-tui's CURSOR_MARKER (an APC sequence) must count as zero-width or the
// main column pad drifts by 5 cells whenever the editor is focused.
// [officina P7] Width helpers delegate to the Rust addon
// (globalThis.__officinaNative, published by _shared/native.ts) when built;
// JS fallbacks below keep output byte-identical without it.
function officinaStripZeroWidth(line) {
    const n = globalThis.__officinaNative;
    if (n) return n.stripAnsi(line);
    return line
        .replace(/\x1b\[[0-9;?]*[a-zA-Z]/g, "")
        .replace(/\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)/g, "")
        .replace(/\x1b_[^\x07\x1b]*(?:\x07|\x1b\\)/g, "");
}
function officinaVisibleWidth(line) {
    const n = globalThis.__officinaNative;
    if (n) return n.visibleWidth(line);
    let w = 0;
    for (const ch of officinaStripZeroWidth(line)) {
        const cp = ch.codePointAt(0) ?? 0;
        w += cp >= 0x1100 && (cp <= 0x115f || (cp >= 0x2e80 && cp <= 0xa4cf) || (cp >= 0xac00 && cp <= 0xd7a3) || (cp >= 0xff00 && cp <= 0xff60)) ? 2 : 1;
    }
    return w;
}
function officinaCut(line, width) {
    const n = globalThis.__officinaNative;
    if (n) return n.cutLine(line, width);
    let vis = 0;
    let out = "";
    let i = 0;
    while (i < line.length) {
        if (line[i] === "\x1b") {
            const rest = line.slice(i);
            const m = /^(\x1b\[[0-9;?]*[a-zA-Z]|\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)|\x1b_[^\x07\x1b]*(?:\x07|\x1b\\))/.exec(rest);
            if (m) {
                out += m[1];
                i += m[1].length;
                continue;
            }
        }
        if (vis >= width) {
            i++;
            continue;
        }
        const cp = line.codePointAt(i) ?? 0;
        const ch = String.fromCodePoint(cp);
        const cw = cp >= 0x1100 && (cp <= 0x115f || (cp >= 0x2e80 && cp <= 0xa4cf) || (cp >= 0xac00 && cp <= 0xd7a3) || (cp >= 0xff00 && cp <= 0xff60)) ? 2 : 1;
        if (vis + cw > width) {
            i += ch.length;
            continue;
        }
        out += ch;
        vis += cw;
        i += ch.length;
    }
    return out;
}
class OfficinaSplit {
    static SIDEBAR_W = 42;
    static COUNT = (globalThis.__officinaSplitCount = (globalThis.__officinaSplitCount ?? 0) + 1); // fits the session panel box (40 cells) + margin
                           // so the frame never wraps or clips
    static GAP = 1;
    static MIN_COLS = 100; // auto-hide below this
    constructor(mode) {
        this.mode = mode;
        this.parts = [
            mode.chatContainer,
            mode.pendingMessagesContainer,
            mode.statusContainer,
            mode.widgetContainerAbove,
            mode.editorContainer,
            mode.widgetContainerBelow,
        ];
        // [officina FOCUS-TEST] env-gated experiment: a handleInput-capable
        // wrapper proves (or refutes) that pi focus routing works for an
        // in-layout component outside the original child set.
        if (process.env.OFFICINA_SIDEBAR_FOCUS_TEST === "1") {
            this.sidebarFocusTarget = new FocusableSidebar(mode.sidebarContainer);
            this.sidebar = this.sidebarFocusTarget;
        } else {
            this.sidebar = mode.sidebarContainer;
        }
        this.editorIndex = 4;
        if (process.env.OFFICINA_SIDEBAR_FOCUS_TEST === "1") console.error("[FOCUS-TEST] OfficinaSplit #" + OfficinaSplit['COUNT'] + " constructed");
    }
    invalidate() {
        for (const p of this.parts) p.invalidate?.();
        this.sidebar.invalidate?.();
    }
    render(width) {
        const m = this.mode;
        const SB_W = OfficinaSplit.SIDEBAR_W;
        const GAP = OfficinaSplit.GAP;
        const sbVisible = width >= OfficinaSplit.MIN_COLS && this.sidebar.children.length > 0;
        // [officina P6] Push sidebar visibility to extensions (globalThis bridge)
        // so extensions can render belowEditor fallbacks when sidebar is hidden.
        if (typeof globalThis.__officinaSidebarVisible === "function") {
            globalThis.__officinaSidebarVisible(sbVisible);
        }
        const mainW = sbVisible ? Math.max(1, width - SB_W - GAP) : width;
        const partLines = this.parts.map((c) => c.render(mainW));
        // [officina P2] fill remaining viewport rows above the editor block.
        const rows = m.ui.terminal.rows ?? 40;
        const outsideRows =
            m.headerContainer.render(width).length +
            m.loadedResourcesContainer.render(width).length +
            m.footer.render(width).length;
        const mainTotal = partLines.reduce((n, ls) => n + ls.length, 0);
        const filler = Math.max(0, rows - outsideRows - mainTotal);
        let mainLines;
        // [officina P10] scrollback mode: render a slice of chat history
        // (offset lines from the live tail) instead of the full tail block.
        // Anchored to the bottom like the live view, with an indicator line.
        if (m.officinaScrollActive && m.officinaScroll > 0 && partLines[0].length > 0) {
            const rest = partLines.slice(1).flat();
            const indicator = theme.fg("dim", "── scrollback · ↑/PgUp older · ↓/PgDn newer · esc return ──");
            const budget = Math.max(3, rows - outsideRows - rest.length - 1);
            const chatTotal = partLines[0].length;
            const end = Math.max(0, chatTotal - m.officinaScroll);
            const start = Math.max(0, end - budget);
            const slice = partLines[0].slice(start, end);
            const pad = Math.max(0, rows - outsideRows - slice.length - 1 - rest.length);
            mainLines = [...new Array(pad).fill(""), ...slice, indicator, ...rest];
        }
        else {
            mainLines = [];
            partLines.forEach((ls, i) => {
                if (i === this.editorIndex && filler > 0) {
                    for (let k = 0; k < filler; k++) mainLines.push("");
                }
                for (const l of ls) mainLines.push(l);
            });
        }
        const sbLines = sbVisible ? this.sidebar.render(SB_W) : [];
        // Sidebar panel background: the theme's panel tone (#161b22) lifted
        // off the #0d1117 substrate (Vitriolum panel color, theme.rs PANEL).
        const SB_BG = "\x1b[48;2;22;27;34m";
        const SB_RESET = "\x1b[0m";
        // [officina P4] BOTTOM-ANCHOR the sidebar. pi-tui's visible viewport is
        // the LAST 'rows' lines of output (tui.js: viewportStart = workingHeight
        // - termHeight), so a top-anchored panel scrolls away as soon as the
        // transcript outgrows the screen — the panel was only visible on a fresh
        // session. Padding ABOVE the sidebar lines pins the panel to the bottom
        // of the emitted block: it stays in every viewport and grows upward.
        const total = Math.max(mainLines.length, sbLines.length);
        const sbPad = Math.max(0, total - sbLines.length);
        // [officina P7] Whole merge loop in one native call when available.
        const n7 = globalThis.__officinaNative;
        if (n7 && typeof n7.mergeSplitRows === "function") {
            return n7.mergeSplitRows({
                mainLines: mainLines,
                mainW: mainW,
                sbLines: sbVisible ? sbLines : [],
                sbW: sbVisible ? SB_W : 0,
                sbPad: sbVisible ? sbPad : 0,
                gap: GAP,
                bg: SB_BG,
                reset: SB_RESET,
                divider: "│",
            });
        }
        const out = [];
        for (let r = 0; r < total; r++) {
            let left = mainLines[r] ?? "";
            if (officinaVisibleWidth(left) > mainW) left = officinaCut(left, mainW);
            let line = left + " ".repeat(Math.max(0, mainW - officinaVisibleWidth(left)));
            if (sbVisible) {
                let right = r >= sbPad ? sbLines[r - sbPad] ?? "" : "";
                if (officinaVisibleWidth(right) > SB_W) right = officinaCut(right, SB_W);
                const pad = Math.max(0, SB_W - officinaVisibleWidth(right));
                // Gap column: coldBlue divider on panel background
                line += SB_BG + "│" + " ".repeat(Math.max(0, GAP - 1)) + SB_BG + right + " ".repeat(pad) + SB_RESET;
            }
            out.push(line);
        }
        return out;
    }
}
// [officina FOCUS-TEST] focusable sidebar wrapper — experiment rig, enabled
// only with OFFICINA_SIDEBAR_FOCUS_TEST=1. Delegates rendering to the real
// sidebar Container; captures typed keys to prove input routing.
class FocusableSidebar {
    focused = false;
    constructor(inner) {
        this.inner = inner;
        this.typed = "";
        this.status = "FOCUS-TEST sidebar (not focused)";
    }
    get children() {
        return this.inner.children;
    }
    invalidate() {
        this.inner.invalidate?.();
    }
    handleInput(data) {
        for (const ch of data) {
            if (ch >= " " && ch <= "~") this.typed += ch;
        }
        this.status = "FOCUS-TEST: " + this.typed.slice(-22);
    }
    render(width) {
        void width;
        return [this.status, ...this.inner.render(width)];
    }
}

`;
src = officinaSplitJs + "\n" + src;

patch(
  "P1 layout",
  `        this.ui.addChild(this.headerContainer);
        this.ui.addChild(this.loadedResourcesContainer);
        this.ui.addChild(this.chatContainer);
        this.ui.addChild(this.pendingMessagesContainer);
        this.ui.addChild(this.statusContainer);
        this.renderWidgets(); // Initialize with default spacer
        this.ui.addChild(this.widgetContainerAbove);
        this.ui.addChild(this.editorContainer);
        this.ui.addChild(this.widgetContainerBelow);
        this.ui.addChild(this.footer);`,
  `        this.ui.addChild(this.headerContainer);
        this.ui.addChild(this.loadedResourcesContainer);
        // [officina P1] docked two-column layout: chat/pending/status/widgets/
        // editor render in the main column, sidebarContainer docks right.
        this.renderWidgets(); // Initialize with default spacer
        this.split = new OfficinaSplit(this);
        this.ui.addChild(this.split);
        this.ui.addChild(this.footer);`,
);

// ── P3: ui.setSidebar plumbing ───────────────────────────────────────────
// The docked sidebar is a dedicated Container rendered by OfficinaSplit
// ([officina P1]), fed by ui.setSidebar(lines) from extensions
// (session-panel).

patch(
  "P3 field",
  `    widgetContainerAbove;
    widgetContainerBelow;`,
  `    widgetContainerAbove;
    widgetContainerBelow;
    // [officina P3] docked sidebar column (fed via ui.setSidebar)
    sidebarContainer;
    // [officina P1] docked two-column split (chat/editor | sidebar)
    split;`,
);

patch(
  "P3 container init",
  `        this.widgetContainerAbove = new Container();
        this.widgetContainerBelow = new Container();`,
  `        this.widgetContainerAbove = new Container();
        this.widgetContainerBelow = new Container();
        // [officina P3] docked sidebar column
        this.sidebarContainer = new Container();`,
);

patch(
  "P3 setter method",
  `    // Maximum total widget lines to prevent viewport overflow`,
  `    // [officina P3] Docked sidebar content from extensions. lines ===
    // undefined clears it. Sidebar uses a higher cap than widgets (full
    // viewport height) since it replaces the below-editor info surface.
    setExtensionSidebar(lines) {
        this.sidebarContainer.clear();
        const maxLines = this.ui?.terminal?.rows ?? 50;
        if (lines && lines.length > 0) {
            for (const line of lines.slice(0, maxLines)) {
                this.sidebarContainer.addChild(new Text(line, 1, 0));
            }
        }
        this.ui.requestRender();
    }
    // Maximum total widget lines to prevent viewport overflow`,
);

patch(
  "P3 ui surface",
  `            setWidget: (key, content, options) => this.setExtensionWidget(key, content, options),`,
  `            setWidget: (key, content, options) => this.setExtensionWidget(key, content, options),
            setSidebar: (lines) => this.setExtensionSidebar(lines),`,
);

// ── P9: dynamic mode tint (editor border consumer) ───────────────────────
// The agent-mode extension publishes globalThis.__officinaModeBorder; the
// editor's borderColor property becomes a live view of it so TAB / /mode
// recolors the chat box immediately.

// ── P10: scrollback navigation + P8 mouse wheel ──────────────────────────
// In docked mode the split repaints a fixed viewport, so chat history never
// reaches the terminal's native scrollback. Intercept PgUp/PgDn/↑/↓/Esc and
// SGR mouse wheel/drag BEFORE the editor; OfficinaSplit renders a history
// slice while active (see P10 block in OfficinaSplit.render).

patch(
  "P9 border consumer + P10/P8 scrollback navigation",
  `        this.editor = this.defaultEditor;
        this.editorContainer = new Container();
        this.editorContainer.addChild(this.editor);`,
  `        this.editor = this.defaultEditor;
        // [officina P9] dynamic mode tint: the editor border property becomes
        // a live view of globalThis.__officinaModeBorder (published by the
        // agent-mode extension), so TAB / /mode recolors the chat box
        // immediately instead of waiting for the next border refresh.
        {
            const ed = this.defaultEditor;
            let borderFn = ed.borderColor;
            try {
                Object.defineProperty(ed, "borderColor", {
                    configurable: true,
                    get() {
                        const tint = globalThis.__officinaModeBorder;
                        return typeof tint === "function" && !this.officinaBorderBypass ? tint : borderFn;
                    },
                    set(v) { borderFn = v; },
                });
            } catch { /* decoration only */ }
        }
        // [officina P10] Scrollback navigation. In docked mode the split repaints
        // a fixed viewport, so chat history never reaches the terminal's native
        // scrollback — PgUp/PgDn previously only scrolled INSIDE multi-line
        // editor text (useless for reading the session). Intercept them before
        // the editor: PgUp enters scrollback mode (view older chat lines),
        // PgDn/↓/PgUp move by page/line, any other key or Esc returns to live.
        // While active, OfficinaSplit renders a slice of chat history instead
        // of the live tail. Up/Down in the (unscrolled) editor already recalls
        // earlier prompts via the pi-tui editor history — unchanged.
        this.officinaScrollActive = false;
        this.officinaScroll = 0;
        {
            const kb = this.keybindings;
            const page = () => Math.max(4, (this.ui.terminal.rows ?? 40) - 8);
            const editor = this.defaultEditor;
            const origHandle = editor.handleInput.bind(editor);
            const apply = (fn) => {
                fn();
                this.split?.invalidate();
                this.ui.requestRender();
            };
            const MOUSE_SGR = new RegExp("^\\u001b\\\\[<(\\\\d+);(\\\\d+);(\\\\d+)([Mm])$");
            let lastDragY = null;
            const scrollBy = (lines) => {
                enterScroll();
                this.officinaScroll = Math.max(0, this.officinaScroll + lines);
                this.split?.invalidate();
                this.ui.requestRender();
            };
            // While scrolling, hide the watermark/custom header: scrolling up
            // brings the document top back into the viewport and the logo
            // rows would sit where history text belongs (owner report
            // 2026-09-01). Restored verbatim on exit.
            const hideHeader = () => {
                if (this.officinaHiddenHeader) return;
                if (this.customHeader) {
                    const idx = this.headerContainer.children.indexOf(this.customHeader);
                    if (idx !== -1) {
                        this.headerContainer.children.splice(idx, 1);
                        this.officinaHiddenHeader = this.customHeader;
                    }
                }
            };
            const restoreHeader = () => {
                if (this.officinaHiddenHeader) {
                    this.headerContainer.children.unshift(this.officinaHiddenHeader);
                    this.officinaHiddenHeader = null;
                }
            };
            const enterScroll = () => {
                if (!this.officinaScrollActive) {
                    this.officinaScrollActive = true;
                    hideHeader();
                }
            };
            const exitScroll = () => {
                this.officinaScrollActive = false;
                this.officinaScroll = 0;
                lastDragY = null;
                restoreHeader();
                this.split?.invalidate();
            };
            editor.handleInput = (data) => {
                // [officina P8] mouse wheel / drag -> scrollback navigation.
                const m = MOUSE_SGR.exec(data);
                if (m) {
                    const button = Number(m[1]);
                    const y = Number(m[3]);
                    const press = m[4] === "M";
                    if (button === 64 && press) { scrollBy(4); return; }   // wheel up
                    if (button === 65 && press) { scrollBy(-4); return; }  // wheel down
                    if ((button & 32) !== 0 && press) {                    // drag/touch motion
                        if (lastDragY !== null) scrollBy(lastDragY - y);
                        lastDragY = y;
                        return;
                    }
                    if ((button & 32) === 0 && press) lastDragY = y;       // drag start
                    if (!press) lastDragY = null;                          // drag ended
                    return; // other mouse events (clicks) are absorbed
                }
                if (kb.matches(data, "tui.editor.pageUp")) {
                    enterScroll();
                    this.officinaScroll += page();
                    apply(() => {});
                    return;
                }
                if (this.officinaScrollActive) {
                    if (kb.matches(data, "tui.editor.pageDown")) {
                        apply(() => {
                            this.officinaScroll = Math.max(0, this.officinaScroll - page());
                            if (this.officinaScroll === 0) this.officinaScrollActive = false;
                        });
                        return;
                    }
                    if (kb.matches(data, "tui.editor.cursorUp")) {
                        enterScroll();
                        this.officinaScroll += 1;
                        apply(() => {});
                        return;
                    }
                    if (kb.matches(data, "tui.editor.cursorDown")) {
                        apply(() => {
                            this.officinaScroll = Math.max(0, this.officinaScroll - 1);
                            if (this.officinaScroll === 0) this.officinaScrollActive = false;
                        });
                        return;
                    }
                    if (data === "\\x1b") {
                        exitScroll();
                        apply(() => {});
                        return;
                    }
                    // any other key: leave scrollback mode, let the key through
                    exitScroll();
                }
                origHandle(data);
            };
        }
        this.editorContainer = new Container();
        this.editorContainer.addChild(this.editor);`,
);

patch(
  "P8 mouse reporting + FOCUS-TEST rig",
  `        this.ui.start();
        this.isInitialized = true;`,
  `        this.ui.start();
        // [officina P8] Enable mouse reporting (button + drag + SGR encoding).
        // pi-tui's stdin-buffer already splits SGR mouse sequences, so they
        // arrive at our editor wrapper intact and drive scrollback: wheel =
        // page-ish steps, drag (touch swipe on phones) = line stepping.
        // Tracking is disabled again in shutdown().
        try {
            process.stdout.write("\x1b[?1000h\x1b[?1002h\x1b[?1006h");
        } catch { /* mouse is enhancement-only */ }
        // [officina FOCUS-TEST] t+6s focus sidebar, t+12s back to editor
        if (process.env.OFFICINA_SIDEBAR_FOCUS_TEST === "1" && this.split?.sidebarFocusTarget) {
            const target = this.split.sidebarFocusTarget;
            setTimeout(() => this.ui.setFocus(target), 6000);
            setTimeout(() => this.ui.setFocus(this.editor), 12000);
        }
        this.isInitialized = true;`,
);

patch(
  "P9 mode-tinted border implementation",
  `    updateEditorBorderColor() {
        if (this.isBashMode) {
            this.editor.borderColor = theme.getBashModeBorderColor();
        }
        else {
            const level = this.session.thinkingLevel || "off";
            this.editor.borderColor = theme.getThinkingBorderColor(level);
        }
        this.ui.requestRender();
    }`,
  `    updateEditorBorderColor() {
        if (this.isBashMode) {
            this.editor.borderColor = theme.getBashModeBorderColor();
        }
        else {
            const level = this.session.thinkingLevel || "off";
            this.editor.borderColor = theme.getThinkingBorderColor(level);
        }
        // [officina P9] mode-tinted border: the active agent mode recolors the
        // chat box (plan gold, build coldBlue, custom per modes.json). Tint is
        // published by the agent-mode extension on globalThis.
        const modeTint = globalThis.__officinaModeBorder;
        if (modeTint && !this.isBashMode) {
            this.editor.borderColor = modeTint;
        }
        this.ui.requestRender();
    }`,
);

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, header + src);

// ── Canary assertions (added 2026-09-01 after the regen-wipe incident) ─────
// Incident: interactive-mode.officina.js carried hand-applied patches (P4
// bottom-anchor, scrollback, P8 mouse, P9 mode tint) that were never captured
// here as anchors. Running this script regenerated the file and silently
// wiped all four committed features (owner bug report 2026-09-01). Rule: a
// patch that exists only in the GENERATED file is a patch waiting to be
// lost — every feature must be an anchored patch HERE, and every patch must
// leave a canary the build asserts on.
const canaries = [
  ["P1 split", "[officina P1] OfficinaSplit"],
  ["P4 bottom-anchor", "[officina P4] BOTTOM-ANCHOR"],
  ["P8 mouse events", "[officina P8] mouse wheel"],
  ["P8 mouse enable", "[officina P8] Enable mouse reporting"],
  ["P9 tint consumer", "[officina P9] dynamic mode tint"],
  ["P9 tint impl", "[officina P9] mode-tinted border"],
  ["P10 scrollback render", "[officina P10] scrollback mode"],
  ["P10 scrollback nav", "[officina P10] Scrollback navigation"],
];
const built = readFileSync(outPath, "utf-8");
for (const [name, marker] of canaries) {
  if (!built.includes(marker)) {
    throw new Error(`build-patch canary FAILED: ${name} (${marker}) missing from output — a patch was lost`);
  }
}
console.log(`[build-patch] canaries ok (${canaries.length})`);
console.log(`[build-patch] wrote ${outPath} (${src.split("\n").length} lines)`);

// ── P5: tool-execution.js display names ────────────────────────────────────
// Copy the upstream tool-execution.js and patch it to use human-readable
// labels (toolDefinition.label) instead of raw tool names for display.
// The hooks.mjs PATCHED map routes imports to this patched copy.
const toolExecSrc = join(here, "..", "node_modules", "@earendil-works", "pi-coding-agent", "dist", "modes", "interactive", "components", "tool-execution.js");
const toolExecOut = join(outDir, "components", "tool-execution.js");
mkdirSync(dirname(toolExecOut), { recursive: true });
let teSrc = readFileSync(toolExecSrc, "utf-8");

function tePatch(name, anchor, replacement) {
  if (!teSrc.includes(anchor)) {
    throw new Error(`P5 patch ${name}: anchor not found in tool-execution.js`);
  }
  teSrc = teSrc.replace(anchor, replacement);
}

tePatch(
  "createCallFallback label",
  `    createCallFallback() {
        return new Text(theme.fg("toolTitle", theme.bold(this.toolName)), 0, 0);
    }`,
  `    createCallFallback() {
        // [officina P5] Use human-readable label from ToolDefinition when available.
        const displayName = this.toolDefinition?.label ?? this.toolName;
        return new Text(theme.fg("toolTitle", theme.bold(displayName)), 0, 0);
    }`,
);

tePatch(
  "formatToolExecution label",
  `    formatToolExecution() {
        let text = theme.fg("toolTitle", theme.bold(this.toolName));`,
  `    formatToolExecution() {
        // [officina P5] Use human-readable label from ToolDefinition when available.
        const displayName = this.toolDefinition?.label ?? this.toolName;
        let text = theme.fg("toolTitle", theme.bold(displayName));`,
);

writeFileSync(toolExecOut, teSrc);
console.log(`[build-patch] wrote ${toolExecOut} (P5 tool display names)`);
