#!/usr/bin/env node
// build-patch.mjs — regenerates runtime/patched/interactive-mode.officina.js
// from the pristine reference + the P1-P3 patch list (layout fork step 2).
//
// Keeping the patch APPLICATION scripted (instead of hand-editing the vendor
// copy) means re-basing on a pi upgrade is: bump the pin, re-run this script,
// fix any anchor that no longer matches. Anchors are asserted — a silent
// partial patch is impossible.
//
// Usage: node ../runtime/build-patch.mjs   (cwd: officina/runtime)

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const refPath = join(here, "upstream", "interactive-mode.reference.js");
const outDir = join(here, "patched");
const outPath = join(outDir, "interactive-mode.officina.js");

let src = readFileSync(refPath, "utf-8");

const header = `// [officina] PATCHED VENDOR COPY - generated by runtime/build-patch.mjs.
// Source: @earendil-works/pi-coding-agent 0.83.0
//         dist/modes/interactive/interactive-mode.js (MIT)
// Pristine reference: runtime/upstream/interactive-mode.reference.js
// Patches applied below are marked with [officina P1..P3]: P1 docked
// two-column split, P2 composer floor-pin, P3 ui.setSidebar plumbing.
// Re-base by re-running build-patch.mjs after bumping the pin; anchors assert.
`;

function patch(name, anchor, replacement) {
  if (!src.includes(anchor)) {
    throw new Error(`patch ${name}: anchor not found`);
  }
  src = src.replace(anchor, replacement);
}

// ── P1: docked two-column layout ──────────────────────────────────────────
// The chat/pending/status/widgets/editor containers are re-parented into an
// OfficinaSplit (bottom of file) which renders main column + docked sidebar
// side-by-side (JS port of runtime/columns.ts, extended for OSC/APC
// zero-width sequences). The header, loaded-resources, and footer stay full
// width. Auto-hides the sidebar below 100 columns.

// ── P2: composer pinned to the viewport floor ────────────────────────────
// The TUI viewport is bottom-anchored, so the composer pins naturally once
// total content fills the screen; OfficinaSplit inserts blank filler rows
// above the editor block to guarantee that on a fresh session (replaces the
// launcher's newline-reserve, which stays as the classic-mode fallback).

// Zero-width-safe width helpers + the split component. Injected at the top
// of the module so the InteractiveMode constructor can reference them.
const officinaSplitJs = String.raw`
// [officina P1] OfficinaSplit — docked two-column layout. JS port of
// runtime/columns.ts (this repo, original work) with OSC/APC-aware widths:
// pi-tui's CURSOR_MARKER (an APC sequence) must count as zero-width or the
// main column pad drifts by 5 cells whenever the editor is focused.
function officinaStripZeroWidth(line) {
    return line
        .replace(/\x1b\[[0-9;?]*[a-zA-Z]/g, "")
        .replace(/\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)/g, "")
        .replace(/\x1b_[^\x07\x1b]*(?:\x07|\x1b\\)/g, "");
}
function officinaVisibleWidth(line) {
    let w = 0;
    for (const ch of officinaStripZeroWidth(line)) {
        const cp = ch.codePointAt(0) ?? 0;
        w += cp >= 0x1100 && (cp <= 0x115f || (cp >= 0x2e80 && cp <= 0xa4cf) || (cp >= 0xac00 && cp <= 0xd7a3) || (cp >= 0xff00 && cp <= 0xff60)) ? 2 : 1;
    }
    return w;
}
function officinaCut(line, width) {
    let vis = 0;
    let out = "";
    let i = 0;
    while (i < line.length) {
        if (line[i] === "\x1b") {
            const rest = line.slice(i);
            const m = /^(\x1b\[[0-9;?]*[a-zA-Z]|\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)|\x1b_[^\x07\x1b]*(?:\x07|\x1b\\))/.exec(rest);
            if (m) {
                out += m[1];
                i += m[1].length;
                continue;
            }
        }
        if (vis >= width) {
            i++;
            continue;
        }
        const cp = line.codePointAt(i) ?? 0;
        const ch = String.fromCodePoint(cp);
        const cw = cp >= 0x1100 && (cp <= 0x115f || (cp >= 0x2e80 && cp <= 0xa4cf) || (cp >= 0xac00 && cp <= 0xd7a3) || (cp >= 0xff00 && cp <= 0xff60)) ? 2 : 1;
        if (vis + cw > width) {
            i += ch.length;
            continue;
        }
        out += ch;
        vis += cw;
        i += ch.length;
    }
    return out;
}
class OfficinaSplit {
    static SIDEBAR_W = 42;
    static COUNT = (globalThis.__officinaSplitCount = (globalThis.__officinaSplitCount ?? 0) + 1); // fits the session panel box (40 cells) + margin
                           // so the frame never wraps or clips
    static GAP = 1;
    static MIN_COLS = 100; // auto-hide below this
    constructor(mode) {
        this.mode = mode;
        this.parts = [
            mode.chatContainer,
            mode.pendingMessagesContainer,
            mode.statusContainer,
            mode.widgetContainerAbove,
            mode.editorContainer,
            mode.widgetContainerBelow,
        ];
        // [officina FOCUS-TEST] env-gated experiment: a handleInput-capable
        // wrapper proves (or refutes) that pi focus routing works for an
        // in-layout component outside the original child set.
        if (process.env.OFFICINA_SIDEBAR_FOCUS_TEST === "1") {
            this.sidebarFocusTarget = new FocusableSidebar(mode.sidebarContainer);
            this.sidebar = this.sidebarFocusTarget;
        } else {
            this.sidebar = mode.sidebarContainer;
        }
        this.editorIndex = 4;
        if (process.env.OFFICINA_SIDEBAR_FOCUS_TEST === "1") console.error("[FOCUS-TEST] OfficinaSplit #" + OfficinaSplit['COUNT'] + " constructed");
    }
    invalidate() {
        for (const p of this.parts) p.invalidate?.();
        this.sidebar.invalidate?.();
    }
    render(width) {
        const m = this.mode;
        const SB_W = OfficinaSplit.SIDEBAR_W;
        const GAP = OfficinaSplit.GAP;
        const sbVisible = width >= OfficinaSplit.MIN_COLS && this.sidebar.children.length > 0;
        const mainW = sbVisible ? Math.max(1, width - SB_W - GAP) : width;
        const partLines = this.parts.map((c) => c.render(mainW));
        // [officina P2] fill remaining viewport rows above the editor block.
        const rows = m.ui.terminal.rows ?? 40;
        const outsideRows =
            m.headerContainer.render(width).length +
            m.loadedResourcesContainer.render(width).length +
            m.footer.render(width).length;
        const mainTotal = partLines.reduce((n, ls) => n + ls.length, 0);
        const filler = Math.max(0, rows - outsideRows - mainTotal);
        const mainLines = [];
        partLines.forEach((ls, i) => {
            if (i === this.editorIndex && filler > 0) {
                for (let k = 0; k < filler; k++) mainLines.push("");
            }
            for (const l of ls) mainLines.push(l);
        });
        const sbLines = sbVisible ? this.sidebar.render(SB_W) : [];
        // Sidebar panel background: the theme's panel tone (#161b22) lifted
        // off the #0d1117 substrate (Vitriolum panel color, theme.rs PANEL).
        const SB_BG = "\x1b[48;2;22;27;34m";
        const SB_RESET = "\x1b[0m";
        const total = Math.max(mainLines.length, sbLines.length);
        const out = [];
        for (let r = 0; r < total; r++) {
            let left = mainLines[r] ?? "";
            if (officinaVisibleWidth(left) > mainW) left = officinaCut(left, mainW);
            let line = left + " ".repeat(Math.max(0, mainW - officinaVisibleWidth(left)));
            if (sbVisible) {
                let right = sbLines[r] ?? "";
                if (officinaVisibleWidth(right) > SB_W) right = officinaCut(right, SB_W);
                const pad = Math.max(0, SB_W - officinaVisibleWidth(right));
                line += " ".repeat(GAP) + SB_BG + right + " ".repeat(pad) + SB_RESET;
            }
            out.push(line);
        }
        return out;
    }
}
// [officina FOCUS-TEST] focusable sidebar wrapper — experiment rig, enabled
// only with OFFICINA_SIDEBAR_FOCUS_TEST=1. Delegates rendering to the real
// sidebar Container; captures typed keys to prove input routing.
class FocusableSidebar {
    focused = false;
    constructor(inner) {
        this.inner = inner;
        this.typed = "";
        this.status = "FOCUS-TEST sidebar (not focused)";
    }
    get children() {
        return this.inner.children;
    }
    invalidate() {
        this.inner.invalidate?.();
    }
    handleInput(data) {
        for (const ch of data) {
            if (ch >= " " && ch <= "~") this.typed += ch;
        }
        this.status = "FOCUS-TEST: " + this.typed.slice(-22);
    }
    render(width) {
        void width;
        return [this.status, ...this.inner.render(width)];
    }
}

`;
src = officinaSplitJs + "\n" + src;

patch(
  "P1 layout",
  `        this.ui.addChild(this.headerContainer);
        this.ui.addChild(this.loadedResourcesContainer);
        this.ui.addChild(this.chatContainer);
        this.ui.addChild(this.pendingMessagesContainer);
        this.ui.addChild(this.statusContainer);
        this.renderWidgets(); // Initialize with default spacer
        this.ui.addChild(this.widgetContainerAbove);
        this.ui.addChild(this.editorContainer);
        this.ui.addChild(this.widgetContainerBelow);
        this.ui.addChild(this.footer);`,
  `        this.ui.addChild(this.headerContainer);
        this.ui.addChild(this.loadedResourcesContainer);
        // [officina P1] docked two-column layout: chat/pending/status/widgets/
        // editor render in the main column, sidebarContainer docks right.
        this.renderWidgets(); // Initialize with default spacer
        this.split = new OfficinaSplit(this);
        this.ui.addChild(this.split);
        this.ui.addChild(this.footer);`,
);

// ── P3: ui.setSidebar plumbing ───────────────────────────────────────────
// The docked sidebar is a dedicated Container rendered by OfficinaSplit
// ([officina P1]), fed by ui.setSidebar(lines) from extensions
// (session-panel).

patch(
  "P3 field",
  `    widgetContainerAbove;
    widgetContainerBelow;`,
  `    widgetContainerAbove;
    widgetContainerBelow;
    // [officina P3] docked sidebar column (fed via ui.setSidebar)
    sidebarContainer;
    // [officina P1] docked two-column split (chat/editor | sidebar)
    split;`,
);

patch(
  "P3 container init",
  `        this.widgetContainerAbove = new Container();
        this.widgetContainerBelow = new Container();`,
  `        this.widgetContainerAbove = new Container();
        this.widgetContainerBelow = new Container();
        // [officina P3] docked sidebar column
        this.sidebarContainer = new Container();`,
);

patch(
  "P3 setter method",
  `    // Maximum total widget lines to prevent viewport overflow`,
  `    // [officina P3] Docked sidebar content from extensions. lines ===
    // undefined clears it. Truncation matches the widget budget.
    setExtensionSidebar(lines) {
        this.sidebarContainer.clear();
        if (lines && lines.length > 0) {
            for (const line of lines.slice(0, InteractiveMode.MAX_WIDGET_LINES)) {
                this.sidebarContainer.addChild(new Text(line, 1, 0));
            }
            if (lines.length > InteractiveMode.MAX_WIDGET_LINES) {
                this.sidebarContainer.addChild(new Text(theme.fg("muted", "... (sidebar truncated)"), 1, 0));
            }
        }
        this.ui.requestRender();
    }
    // Maximum total widget lines to prevent viewport overflow`,
);

patch(
  "P3 ui surface",
  `            setWidget: (key, content, options) => this.setExtensionWidget(key, content, options),`,
  `            setWidget: (key, content, options) => this.setExtensionWidget(key, content, options),
            setSidebar: (lines) => this.setExtensionSidebar(lines),`,
);

patch(
  "FOCUS-TEST rig",
  `        this.ui.start();
        this.isInitialized = true;`,
  `        this.ui.start();
        // [officina FOCUS-TEST] t+6s focus sidebar, t+12s back to editor
        if (process.env.OFFICINA_SIDEBAR_FOCUS_TEST === "1" && this.split?.sidebarFocusTarget) {
            const target = this.split.sidebarFocusTarget;
            setTimeout(() => this.ui.setFocus(target), 6000);
            setTimeout(() => this.ui.setFocus(this.editor), 12000);
        }
        this.isInitialized = true;`,
);

mkdirSync(outDir, { recursive: true });
writeFileSync(outPath, header + src);
console.log(`[build-patch] wrote ${outPath} (${src.split("\n").length} lines)`);
